name: Test PR

on:
  pull_request

jobs:
    check:
        steps:
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
