name: Test-Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "30 10 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get timestamp
        run: |
          mkdir deploy || true
          echo "Auto-deployment" > deploy/README.md
          date -u +%Y-%m-%dT%H:%M:%S >> deploy/README.md
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:abitmore/test-github-deployment.git
          BRANCH: main
          FOLDER: deploy
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_FOR_DEPLOY_TEST_REPO }}
