name: Test concurrency

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    name: Job 1
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        es: [ "es7", "es8" ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    # this is buggy, 4 runs are brought up, but 2 of them are canceled
    # see https://github.com/community/community/discussions/5435
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo OS and ES version
        run: echo ${{ matrix.os }} ${{ matrix.es }}
