name: Test-self-update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "48 20 * * 5"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: abitmore/keepalive-workflow@master
      with:
        time_elapsed: -1
        committer_username: abitmore
        committer_email: abitmore@users.noreply.github.com
        gh_token: ${{ secrets.GITHUB_TOKEN }}
