name: Test-self-update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "15 20 * * 5"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get timestamp
      run: |
        mkdir deploy || true
        echo "Auto-deployment" > deploy/README.md
        echo "---------------" >> deploy/README.md
        date -u +%Y-%m-%dT%H:%M:%S >> deploy/README.md
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: update-time
        FOLDER: deploy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
