name: Test matrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    name: Job 1
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    outputs:
      runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  job2:
    name: Job 2
    needs: job1
    strategy:
      matrix:
        es: [ "es7", "es8" ]
    runs-on: ${{ needs.job1.runs-on }}
    steps:
      - name: Echo ES version
        run: echo ${{ matrix.es }}
